// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: internal/adapters/driven/rpc/tosaver/proto/svc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SaverClient is the client API for Saver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SaverClient interface {
	SinglePart(ctx context.Context, in *TextFieldReq, opts ...grpc.CallOption) (*TextFieldRes, error)
	MultiPart(ctx context.Context, opts ...grpc.CallOption) (Saver_MultiPartClient, error)
}

type saverClient struct {
	cc grpc.ClientConnInterface
}

func NewSaverClient(cc grpc.ClientConnInterface) SaverClient {
	return &saverClient{cc}
}

func (c *saverClient) SinglePart(ctx context.Context, in *TextFieldReq, opts ...grpc.CallOption) (*TextFieldRes, error) {
	out := new(TextFieldRes)
	err := c.cc.Invoke(ctx, "/rpc.Saver/singlePart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saverClient) MultiPart(ctx context.Context, opts ...grpc.CallOption) (Saver_MultiPartClient, error) {
	stream, err := c.cc.NewStream(ctx, &Saver_ServiceDesc.Streams[0], "/rpc.Saver/multiPart", opts...)
	if err != nil {
		return nil, err
	}
	x := &saverMultiPartClient{stream}
	return x, nil
}

type Saver_MultiPartClient interface {
	Send(*FileUploadReq) error
	CloseAndRecv() (*FileUploadRes, error)
	grpc.ClientStream
}

type saverMultiPartClient struct {
	grpc.ClientStream
}

func (x *saverMultiPartClient) Send(m *FileUploadReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *saverMultiPartClient) CloseAndRecv() (*FileUploadRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FileUploadRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SaverServer is the server API for Saver service.
// All implementations must embed UnimplementedSaverServer
// for forward compatibility
type SaverServer interface {
	SinglePart(context.Context, *TextFieldReq) (*TextFieldRes, error)
	MultiPart(Saver_MultiPartServer) error
	mustEmbedUnimplementedSaverServer()
}

// UnimplementedSaverServer must be embedded to have forward compatible implementations.
type UnimplementedSaverServer struct {
}

func (UnimplementedSaverServer) SinglePart(context.Context, *TextFieldReq) (*TextFieldRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SinglePart not implemented")
}
func (UnimplementedSaverServer) MultiPart(Saver_MultiPartServer) error {
	return status.Errorf(codes.Unimplemented, "method MultiPart not implemented")
}
func (UnimplementedSaverServer) mustEmbedUnimplementedSaverServer() {}

// UnsafeSaverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SaverServer will
// result in compilation errors.
type UnsafeSaverServer interface {
	mustEmbedUnimplementedSaverServer()
}

func RegisterSaverServer(s grpc.ServiceRegistrar, srv SaverServer) {
	s.RegisterService(&Saver_ServiceDesc, srv)
}

func _Saver_SinglePart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextFieldReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaverServer).SinglePart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Saver/singlePart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaverServer).SinglePart(ctx, req.(*TextFieldReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Saver_MultiPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SaverServer).MultiPart(&saverMultiPartServer{stream})
}

type Saver_MultiPartServer interface {
	SendAndClose(*FileUploadRes) error
	Recv() (*FileUploadReq, error)
	grpc.ServerStream
}

type saverMultiPartServer struct {
	grpc.ServerStream
}

func (x *saverMultiPartServer) SendAndClose(m *FileUploadRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *saverMultiPartServer) Recv() (*FileUploadReq, error) {
	m := new(FileUploadReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Saver_ServiceDesc is the grpc.ServiceDesc for Saver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Saver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Saver",
	HandlerType: (*SaverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "singlePart",
			Handler:    _Saver_SinglePart_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "multiPart",
			Handler:       _Saver_MultiPart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/adapters/driven/rpc/tosaver/proto/svc.proto",
}
